export const DataTable = {
  AccountAdmin: [
    "STT",
    "Họ và Tên",
    "Email",
    "Số điện thoại",
    "Ngày tham gia",
    "Giới tính",
    "Trạng thái",
    "Tác vụ",
  ],
  AccountExpert: [
    "STT",
    "Họ và Tên",
    "Email",
    "Ngày sinh",
    "Số điện thoại",
    "Ngày tham gia",
    "Giới tính",
    "Trạng thái",
    "Tác vụ",
  ],
  Blog: ["STT", "Tựa đề", "Phân loại", "Ngày đăng", "Người đăng", "Trạng thái", "Tác vụ"],
  HistoryAdvise: ["STT", "Thời gian", "Mã tài khoản", "Lịch sử nội dung cuộc trò chuyện"],
};
