export const DataTable = {
  Transaction: ["STT", "Thời gian tạo", "Mail", "Gói", "Giảm giá", "Giá trị"],
  Family: [
    "STT",
    "Thời gian tạo",
    "Mail",
    "Tên gia đình",
    "Số tk kích hoạt",
    "Trạng thái",
    "Tác vụ",
  ],
  AccountFamily: ["STT", "Tên", "Vai trò", "Giới tính", "Năm sinh"],
  History: [
    "STT",
    "Thời gian tạo",
    "Mail tài khoản gia đình",
    "Thành viên đặt câu hỏi",
    "Log nội dung",
  ],
  Report: ["STT", "Thời gian tạo", "Mail", "Lý do báo cáo", "Trạng thái", "Check log", "Tác vụ"],
  Notification: ["STT", "Thời gian tạo", "Thời gian đăng", "Tựa đề", "Đối tượng nhận", "Tác vụ"],

  Discount: [
    "STT",
    "Thời gian bắt đầu",
    "Thời gian kết thúc",
    "Gói",
    "Giảm giá",
    "Giá bán",
    "Giá gốc",
    "Trạng thái",
    "Tác vụ",
  ],
  Asset: [
    "STT",
    "Thời gian tạo",
    "Hình ảnh",
    "Hình ảnh thực tế",
    "Tên",
    "Loại",
    "Giá",
    "Trạng thái",
    "Tác vụ",
  ],
  Task_type: ["STT", "Thời gian tạo", "Ảnh nhỏ", "Ảnh to", "Tên", "Phân loại", "Tác vụ"],
  Quiz: [
    "STT",
    "Thời gian tạo",
    "Tựa đề",
    "Phân loại",
    "Nhóm độ tuổi",
    "Số câu hỏi",
    "Blog",
    "Trạng thái",
    "Tác vụ",
  ],
  Blog: ["STT", "Thời gian tạo", "Tựa đề", "Thuộc bộ câu hỏi", "Tác vụ"],
  Prompt: [
    "STT",
    "Thời gian tạo",
    "Nội dung",
    "Từ khoá",
    "Số ký tự",
    "Trạng thái",
    "Tác vụ",
  ],
};
